---
title: "Final Grade Reflection"
author: "Zarina Yunis"
format: docx
editor: visual
---

In this document, you make a data-based argument for the grade you've earned in this course. Your argument should include evidence from the supporting artifacts you've provided.

## The output document should be a PDF or a Word Document, as it should be a **maximum** of 2-pages.

I earned an A- in STAT 331.

**WD-1:** Lab 2 Question 1, Practice Activity 4, Question 1

**WD-2:** Lab 3, Question 7

**WD-3:** Lab 3, Question 9 (Familiar Words)

**WD-4:** Lab 3 Question 4, Lab 4 Question 7

**WD-5:** Preview Activity: Reshaping and Joining Data, Questions 2 and 3

**WD-6:** Lab 4, Question 2

**WD-7:** Lab 4 Question 6, Lab 4 Question 7

**R-1:** Lab 2, YAML and Set Up

**R-2:** Lab 7, Question 4

**R-3:** Lab 4 Question 3

**DVS-1:** Lab 2, Question 5

**DVS-2:** Lab 2, Question 6

**DVS-3:** Lab 2, Question 7

**DVS-4:** Lab 3, Question 7

**DVS-5:** Lab 3, Question 4

**DVS-6:** Challenge 9, Question 5 (refer to the numbers on my document)

**DVS-7:** Challenge 9, Question 11 (refer to the numbers on my document)

**PE-1:** Lab 7, Question 1

**PE-2:** Lab 7, Question 3

**PE-3:** Lab 8, Question 7 (refer to the numbers on my document)

**DSM-1:** Lab 9, Question 5 (Refer to Challenge 9 file)

**DSM-2:** Lab 9, Questions 6 and 7 (Refer to Challenge 9 file)

In addition to meeting a majority of the learning targets in my practice, lab, and challenge assignments, I have tried to help out other people in my class for the concepts I have mastered. I am an active participant in my group chat for my STAT 331 class group, as I ask my peers questions when I need help and I respond to their questions when they need help. I am fortunate to have a supportive group of peers in my class, as we bounce ideas off of each other and have helped each other grow as data scientists.

While STAT 331 continues to be a difficult course for me, I have accomplished several of my academic goals already. I continue to look for outside resources to help when concepts do not make sense to me. I have responded to most of my requested revisions in a timely manner, and I take my revisions seriously. When I do not understand the material being taught to me, I always ask Dr. Theobold or one of my peers rather than keeping to myself. My continued dedication to this course has led me towards proficiency in most of the learning targets. Since I have spent a lot of time wrestling with the concepts, I have developed a solid understanding of what was taught. While I am not perfect and will continue to grow, I believe my mastery of most of the learning targets and my continued effort to comprehend the material has earned me an A- in STAT 331.
